### ISSUE TITLE
INVALID FRAME

### ISSUE THREAD

**Issue by albflo** [weirdgyn/LeptonVid#1]
Hi,

I am currently using your implementation on a RPi 0 W (Raspbian with 4.19.118+) with a Lepton 3.5 and the original breakout board v1.4 and v2. I was able to set everything up and I am able to run your script, but I can't get any frames. By activating DEBUG mode I am able to see that the IRQ are received, but it always tells me that it received a INVALID FRAME. The error gets caused in the `LeptonVid.c` file at line 124 where:

`ret = ioctl(fd, SPI_IOC_MESSAGE(1), &tr);`

returns -1. Did you or someone else experience a problem like that? Overall the wiring doesn't show any problems for `/dev/spidev0.0` and the i2c bus and I use 20 cm long wires which shouldn't be too long for this.

**Comment by albflo** [comment]
Okay now I tested it on the v2 board and it works on that, but not on the v1.4.

**Comment by weirdgyn** [comment]
Try again with 1.4 and check Lepton module to correctly fit inside board socket I found it to be the cause of malfunction in 90% of cases.

**Comment by albflo** [comment]
Sry for the late responds, yes it helped to replug the camera again, now it works on the v1.4 too!
That's great, I looked into that approach and it could be possible to cross compile the RPi0 kernel to add those FLIR modules. I will let you know if I do that and if it was successful!
